[package]
name = "learning"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
chrono = "0.4"
tokio = { version = "1.41", features = [ "full" ]}
sqlx = { version = "0.8", features = [ "postgres", "runtime-tokio-rustls" ]}
tracing = "0.1"
tracing-subscriber = "0.3"